#!/usr/bin/expect

spawn codehawk

expect "Please enter your email (must match the one used to sign up with Hawk):\n"
send "travis@codehawk.app"

expect "Please enter your account auth token:\n"
send "travis-fake-auth-token"

expect "Unable to find git data, please re-run in a git repository."