#!/bin/bash
set -euo pipefail

# Pull down bats
if [ ! -d "tests/bats" ] ; then
    echo "Pulling down github.com/sstephenson/bats test framework..."
    git clone https://github.com/sstephenson/bats.git tests/bats
fi

# Run tests
# echo "Attempting to run bats tests..."
# tests/bats/bin/bats tests

apt-get install expect

spawn codehawk

expect "Please enter your email (must match the one used to sign up with Hawk):\n"
send "travis@codehawk.app"

expect "Please enter your account auth token:\n"
send "travis-fake-auth-token"

expect "Unable to find git data, please re-run in a git repository."