#!/bin/bash
set -euo pipefail

# Pull down bats
if [ ! -d "tests/bats" ] ; then
    echo "Pulling down github.com/sstephenson/bats test framework..."
    git clone https://github.com/sstephenson/bats.git tests/bats
fi

# Run tests
# echo "Attempting to run bats tests..."
# tests/bats/bin/bats tests

./expects